sudo: required
services:
    - docker
    - node_js: "11.10.1"

before_install:
    - docker build -t vkas288/frontend -f Dockerfile.dev .

script:
    - docker run vkas288/frontend npm run test -- --coverage
