sudo: required
services:
    - docker

before_install:
    - docker build -t vkas288/frontend -f Dockerfile.dev .

script:
    - docker run vkas288/frontend npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-us-east-1-439462370694"
    bucket_path: "frontend"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
